---
- name: Deploy buildconfig-s2i
  when: with_deploy | default(false) | bool
  include_tasks: deploy.yml

- name: Validate buildconfig-s2i on source
  when: with_validate_source | default(false) | bool
  include_tasks: validate.yml

- name: Cleanup buildconfig-s2i
  when: with_cleanup | default(false) | bool
  include_tasks: remove.yml
