---
- name: Validate api-s2i BuildConfig exists
  k8s_info:
    host: "{{ server }}"
    api_key: "{{ token }}"
    verify_ssl: "{{ verify_ssl }}"
    api_version: build.openshift.io/v1
    kind: BuildConfig
    name: api-s2i
    namespace: "{{ namespace }}"
  register: buildconfig_result
  failed_when: buildconfig_result.resources | length == 0
