---
- name: Check webapp-docker BuildConfig exists
  k8s_info:
    host: "{{ server }}"
    api_key: "{{ token }}"
    verify_ssl: "{{ verify_ssl }}"
    api_version: build.openshift.io/v1
    kind: BuildConfig
    name: webapp-docker
    namespace: "{{ namespace }}"
  register: webapp_bc
  until: webapp_bc.resources|default([])|length == 1
  retries: 10
  delay: 3

- name: Check api-s2i BuildConfig exists
  k8s_info:
    host: "{{ server }}"
    api_key: "{{ token }}"
    verify_ssl: "{{ verify_ssl }}"
    api_version: build.openshift.io/v1
    kind: BuildConfig
    name: api-s2i
    namespace: "{{ namespace }}"
  register: api_bc
  until: api_bc.resources|default([])|length == 1
  retries: 10
  delay: 3

- name: Check docker-envvars BuildConfig exists
  k8s_info:
    host: "{{ server }}"
    api_key: "{{ token }}"
    verify_ssl: "{{ verify_ssl }}"
    api_version: build.openshift.io/v1
    kind: BuildConfig
    name: docker-envvars
    namespace: "{{ namespace }}"
  register: envvars_bc
  until: envvars_bc.resources|default([])|length == 1
  retries: 10
  delay: 3
