---
- name: Delete webapp-docker BuildConfig
  k8s:
    host: "{{ server }}"
    api_key: "{{ token }}"
    verify_ssl: "{{ verify_ssl }}"
    state: absent
    api_version: build.openshift.io/v1
    kind: BuildConfig
    name: webapp-docker
    namespace: "{{ namespace }}"
  ignore_errors: yes

- name: Delete ImageStream
  k8s:
    host: "{{ server }}"
    api_key: "{{ token }}"
    verify_ssl: "{{ verify_ssl }}"
    state: absent
    api_version: image.openshift.io/v1
    kind: ImageStream
    name: webapp-docker
    namespace: "{{ namespace }}"
  ignore_errors: yes

- name: Delete namespace
  k8s:
    state: absent
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: "{{ namespace }}"
    host: "{{ server }}"
    api_key: "{{ token }}"
    verify_ssl: "{{ verify_ssl }}"
  when: non_admin_user == false
  ignore_errors: yes
