---
- name: Delete Cassandra StatefulSet
  k8s:
    state: absent
    definition:
      apiVersion: apps/v1
      kind: StatefulSet
      metadata:
        name: "{{ app_name }}"
        namespace: "{{ namespace }}"
    context: "{{ context | default(omit) }}"
    host: "{{ server if (token | default('') | string | length) > 0 else omit }}"
    api_key: "{{ token if (token | default('') | string | length) > 0 else omit }}"
    verify_ssl: "{{ verify_ssl }}"

- name: Delete Cassandra service
  k8s:
    state: absent
    definition:
      apiVersion: v1
      kind: Service
      metadata:
        name: "{{ app_name }}"
        namespace: "{{ namespace }}"
    context: "{{ context | default(omit) }}"
    host: "{{ server if (token | default('') | string | length) > 0 else omit }}"
    api_key: "{{ token if (token | default('') | string | length) > 0 else omit }}"
    verify_ssl: "{{ verify_ssl }}"
